version: '3.5'
networks:
    baadist_default:
        driver: bridge
        name: baadist_default

services:
    zookeeper:
      image: confluentinc/cp-zookeeper:5.5.0
      hostname: zookeeper
      container_name: zookeeper
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
      networks:
        - baadist_default

    kafka:
      image: confluentinc/cp-kafka:5.5.0
      hostname: kafka
      container_name: kafka
      depends_on:
        - zookeeper
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      networks:
        - baadist_default

    vomci:
      image: obbaa-vomci
      hostname: obbaa-vomci
      container_name: obbaa-vomci
      ports:
        - 8801:8801
        - 58433:58433
      environment:
        GRPC_SERVER_NAME: obbaa-vomci
        LOCAL_GRPC_SERVER_PORT: 58433
        # Kafka bootstrap server, please provide only one address
        KAFKA_BOOTSTRAP_SERVER: "kafka:9092 localhost:9092"
        # List of Consumer topics, seperated by spaces
        KAFKA_REQUEST_TOPICS: "VOMCI_REQUEST"
        KAFKA_RESPONSE_TOPICS: "VOMCI_RESPONSE"
        KAFKA_NOTIFICATION_TOPICS: "VOMCI_NOTIFICATION"
        VOMCI_KAFKA_SENDER_NAME: "bbf-vomci"
        VOMCI_KAFKA_VOLTMF_NAME: "vOLTMF"
      networks:
        - baadist_default
      volumes:
        - /baa/stores/vomci-function-db:/db
      depends_on:
        - zookeeper
        - kafka
