# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tr451_vomci_function_sbi_message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tr451_vomci_function_sbi_message.proto',
  package='tr451_vomci_function_sbi_message',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n&tr451_vomci_function_sbi_message.proto\x12 tr451_vomci_function_sbi_message\"(\n\x12VomciFunctionHello\x12\x12\n\nvomci_name\x18\x01 \x01(\t\"\x1c\n\x08OltHello\x12\x10\n\x08olt_name\x18\x01 \x01(\t\"\xb6\x01\n\x11HelloVomciRequest\x12N\n\x0evomci_function\x18\x01 \x01(\x0b\x32\x34.tr451_vomci_function_sbi_message.VomciFunctionHelloH\x00\x12\x39\n\x03olt\x18\x02 \x01(\x0b\x32*.tr451_vomci_function_sbi_message.OltHelloH\x00\x42\x16\n\x14local_endpoint_hello\"\xb8\x01\n\x12HelloVomciResponse\x12N\n\x0evomci_function\x18\x01 \x01(\x0b\x32\x34.tr451_vomci_function_sbi_message.VomciFunctionHelloH\x00\x12\x39\n\x03olt\x18\x02 \x01(\x0b\x32*.tr451_vomci_function_sbi_message.OltHelloH\x00\x42\x17\n\x15remote_endpoint_hello\"E\n\nOmciPacket\x12\x0e\n\x06onu_id\x18\x01 \x01(\t\x12\x16\n\x0e\x63hnl_term_name\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\x62\x06proto3'
)




_VOMCIFUNCTIONHELLO = _descriptor.Descriptor(
  name='VomciFunctionHello',
  full_name='tr451_vomci_function_sbi_message.VomciFunctionHello',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vomci_name', full_name='tr451_vomci_function_sbi_message.VomciFunctionHello.vomci_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=116,
)


_OLTHELLO = _descriptor.Descriptor(
  name='OltHello',
  full_name='tr451_vomci_function_sbi_message.OltHello',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='olt_name', full_name='tr451_vomci_function_sbi_message.OltHello.olt_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=146,
)


_HELLOVOMCIREQUEST = _descriptor.Descriptor(
  name='HelloVomciRequest',
  full_name='tr451_vomci_function_sbi_message.HelloVomciRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vomci_function', full_name='tr451_vomci_function_sbi_message.HelloVomciRequest.vomci_function', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='olt', full_name='tr451_vomci_function_sbi_message.HelloVomciRequest.olt', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='local_endpoint_hello', full_name='tr451_vomci_function_sbi_message.HelloVomciRequest.local_endpoint_hello',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=149,
  serialized_end=331,
)


_HELLOVOMCIRESPONSE = _descriptor.Descriptor(
  name='HelloVomciResponse',
  full_name='tr451_vomci_function_sbi_message.HelloVomciResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vomci_function', full_name='tr451_vomci_function_sbi_message.HelloVomciResponse.vomci_function', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='olt', full_name='tr451_vomci_function_sbi_message.HelloVomciResponse.olt', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='remote_endpoint_hello', full_name='tr451_vomci_function_sbi_message.HelloVomciResponse.remote_endpoint_hello',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=334,
  serialized_end=518,
)


_OMCIPACKET = _descriptor.Descriptor(
  name='OmciPacket',
  full_name='tr451_vomci_function_sbi_message.OmciPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='onu_id', full_name='tr451_vomci_function_sbi_message.OmciPacket.onu_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chnl_term_name', full_name='tr451_vomci_function_sbi_message.OmciPacket.chnl_term_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='tr451_vomci_function_sbi_message.OmciPacket.payload', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=520,
  serialized_end=589,
)

_HELLOVOMCIREQUEST.fields_by_name['vomci_function'].message_type = _VOMCIFUNCTIONHELLO
_HELLOVOMCIREQUEST.fields_by_name['olt'].message_type = _OLTHELLO
_HELLOVOMCIREQUEST.oneofs_by_name['local_endpoint_hello'].fields.append(
  _HELLOVOMCIREQUEST.fields_by_name['vomci_function'])
_HELLOVOMCIREQUEST.fields_by_name['vomci_function'].containing_oneof = _HELLOVOMCIREQUEST.oneofs_by_name['local_endpoint_hello']
_HELLOVOMCIREQUEST.oneofs_by_name['local_endpoint_hello'].fields.append(
  _HELLOVOMCIREQUEST.fields_by_name['olt'])
_HELLOVOMCIREQUEST.fields_by_name['olt'].containing_oneof = _HELLOVOMCIREQUEST.oneofs_by_name['local_endpoint_hello']
_HELLOVOMCIRESPONSE.fields_by_name['vomci_function'].message_type = _VOMCIFUNCTIONHELLO
_HELLOVOMCIRESPONSE.fields_by_name['olt'].message_type = _OLTHELLO
_HELLOVOMCIRESPONSE.oneofs_by_name['remote_endpoint_hello'].fields.append(
  _HELLOVOMCIRESPONSE.fields_by_name['vomci_function'])
_HELLOVOMCIRESPONSE.fields_by_name['vomci_function'].containing_oneof = _HELLOVOMCIRESPONSE.oneofs_by_name['remote_endpoint_hello']
_HELLOVOMCIRESPONSE.oneofs_by_name['remote_endpoint_hello'].fields.append(
  _HELLOVOMCIRESPONSE.fields_by_name['olt'])
_HELLOVOMCIRESPONSE.fields_by_name['olt'].containing_oneof = _HELLOVOMCIRESPONSE.oneofs_by_name['remote_endpoint_hello']
DESCRIPTOR.message_types_by_name['VomciFunctionHello'] = _VOMCIFUNCTIONHELLO
DESCRIPTOR.message_types_by_name['OltHello'] = _OLTHELLO
DESCRIPTOR.message_types_by_name['HelloVomciRequest'] = _HELLOVOMCIREQUEST
DESCRIPTOR.message_types_by_name['HelloVomciResponse'] = _HELLOVOMCIRESPONSE
DESCRIPTOR.message_types_by_name['OmciPacket'] = _OMCIPACKET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VomciFunctionHello = _reflection.GeneratedProtocolMessageType('VomciFunctionHello', (_message.Message,), {
  'DESCRIPTOR' : _VOMCIFUNCTIONHELLO,
  '__module__' : 'tr451_vomci_function_sbi_message_pb2'
  # @@protoc_insertion_point(class_scope:tr451_vomci_function_sbi_message.VomciFunctionHello)
  })
_sym_db.RegisterMessage(VomciFunctionHello)

OltHello = _reflection.GeneratedProtocolMessageType('OltHello', (_message.Message,), {
  'DESCRIPTOR' : _OLTHELLO,
  '__module__' : 'tr451_vomci_function_sbi_message_pb2'
  # @@protoc_insertion_point(class_scope:tr451_vomci_function_sbi_message.OltHello)
  })
_sym_db.RegisterMessage(OltHello)

HelloVomciRequest = _reflection.GeneratedProtocolMessageType('HelloVomciRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOVOMCIREQUEST,
  '__module__' : 'tr451_vomci_function_sbi_message_pb2'
  # @@protoc_insertion_point(class_scope:tr451_vomci_function_sbi_message.HelloVomciRequest)
  })
_sym_db.RegisterMessage(HelloVomciRequest)

HelloVomciResponse = _reflection.GeneratedProtocolMessageType('HelloVomciResponse', (_message.Message,), {
  'DESCRIPTOR' : _HELLOVOMCIRESPONSE,
  '__module__' : 'tr451_vomci_function_sbi_message_pb2'
  # @@protoc_insertion_point(class_scope:tr451_vomci_function_sbi_message.HelloVomciResponse)
  })
_sym_db.RegisterMessage(HelloVomciResponse)

OmciPacket = _reflection.GeneratedProtocolMessageType('OmciPacket', (_message.Message,), {
  'DESCRIPTOR' : _OMCIPACKET,
  '__module__' : 'tr451_vomci_function_sbi_message_pb2'
  # @@protoc_insertion_point(class_scope:tr451_vomci_function_sbi_message.OmciPacket)
  })
_sym_db.RegisterMessage(OmciPacket)


# @@protoc_insertion_point(module_scope)
