# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tr451_vomci_function_sbi_service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import tr451_vomci_function_sbi_message_pb2 as tr451__vomci__function__sbi__message__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tr451_vomci_function_sbi_service.proto',
  package='tr451_vomci_function_sbi_service',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n&tr451_vomci_function_sbi_service.proto\x12 tr451_vomci_function_sbi_service\x1a\x1bgoogle/protobuf/empty.proto\x1a&tr451_vomci_function_sbi_message.proto2\x8f\x01\n\x14OmciFunctionHelloSbi\x12w\n\nHelloVomci\x12\x33.tr451_vomci_function_sbi_message.HelloVomciRequest\x1a\x34.tr451_vomci_function_sbi_message.HelloVomciResponse2\xc3\x01\n\x16OmciFunctionMessageSbi\x12Y\n\x0fListenForOmciRx\x12\x16.google.protobuf.Empty\x1a,.tr451_vomci_function_sbi_message.OmciPacket0\x01\x12N\n\x06OmciTx\x12,.tr451_vomci_function_sbi_message.OmciPacket\x1a\x16.google.protobuf.Emptyb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,tr451__vomci__function__sbi__message__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_OMCIFUNCTIONHELLOSBI = _descriptor.ServiceDescriptor(
  name='OmciFunctionHelloSbi',
  full_name='tr451_vomci_function_sbi_service.OmciFunctionHelloSbi',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=146,
  serialized_end=289,
  methods=[
  _descriptor.MethodDescriptor(
    name='HelloVomci',
    full_name='tr451_vomci_function_sbi_service.OmciFunctionHelloSbi.HelloVomci',
    index=0,
    containing_service=None,
    input_type=tr451__vomci__function__sbi__message__pb2._HELLOVOMCIREQUEST,
    output_type=tr451__vomci__function__sbi__message__pb2._HELLOVOMCIRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_OMCIFUNCTIONHELLOSBI)

DESCRIPTOR.services_by_name['OmciFunctionHelloSbi'] = _OMCIFUNCTIONHELLOSBI


_OMCIFUNCTIONMESSAGESBI = _descriptor.ServiceDescriptor(
  name='OmciFunctionMessageSbi',
  full_name='tr451_vomci_function_sbi_service.OmciFunctionMessageSbi',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=292,
  serialized_end=487,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListenForOmciRx',
    full_name='tr451_vomci_function_sbi_service.OmciFunctionMessageSbi.ListenForOmciRx',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=tr451__vomci__function__sbi__message__pb2._OMCIPACKET,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='OmciTx',
    full_name='tr451_vomci_function_sbi_service.OmciFunctionMessageSbi.OmciTx',
    index=1,
    containing_service=None,
    input_type=tr451__vomci__function__sbi__message__pb2._OMCIPACKET,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_OMCIFUNCTIONMESSAGESBI)

DESCRIPTOR.services_by_name['OmciFunctionMessageSbi'] = _OMCIFUNCTIONMESSAGESBI

# @@protoc_insertion_point(module_scope)
