# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tr451_vomci_sbi_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import tr451_vomci_sbi_message_pb2 as tr451__vomci__sbi__message__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tr451_vomci_sbi_service.proto',
  package='tr451_vomci_sbi_service.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1dtr451_vomci_sbi_service.proto\x12\x1atr451_vomci_sbi_service.v1\x1a\x1dtr451_vomci_sbi_message.proto\x1a\x1bgoogle/protobuf/empty.proto2|\n\rVomciHelloSbi\x12k\n\nHelloVomci\x12-.tr451_vomci_sbi_message.v1.HelloVomciRequest\x1a..tr451_vomci_sbi_message.v1.HelloVomciResponse2\xb6\x01\n\x0fVomciMessageSbi\x12V\n\x10ListenForVomciRx\x12\x16.google.protobuf.Empty\x1a(.tr451_vomci_sbi_message.v1.VomciMessage0\x01\x12K\n\x07VomciTx\x12(.tr451_vomci_sbi_message.v1.VomciMessage\x1a\x16.google.protobuf.Emptyb\x06proto3'
  ,
  dependencies=[tr451__vomci__sbi__message__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_VOMCIHELLOSBI = _descriptor.ServiceDescriptor(
  name='VomciHelloSbi',
  full_name='tr451_vomci_sbi_service.v1.VomciHelloSbi',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=121,
  serialized_end=245,
  methods=[
  _descriptor.MethodDescriptor(
    name='HelloVomci',
    full_name='tr451_vomci_sbi_service.v1.VomciHelloSbi.HelloVomci',
    index=0,
    containing_service=None,
    input_type=tr451__vomci__sbi__message__pb2._HELLOVOMCIREQUEST,
    output_type=tr451__vomci__sbi__message__pb2._HELLOVOMCIRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_VOMCIHELLOSBI)

DESCRIPTOR.services_by_name['VomciHelloSbi'] = _VOMCIHELLOSBI


_VOMCIMESSAGESBI = _descriptor.ServiceDescriptor(
  name='VomciMessageSbi',
  full_name='tr451_vomci_sbi_service.v1.VomciMessageSbi',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=248,
  serialized_end=430,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListenForVomciRx',
    full_name='tr451_vomci_sbi_service.v1.VomciMessageSbi.ListenForVomciRx',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=tr451__vomci__sbi__message__pb2._VOMCIMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='VomciTx',
    full_name='tr451_vomci_sbi_service.v1.VomciMessageSbi.VomciTx',
    index=1,
    containing_service=None,
    input_type=tr451__vomci__sbi__message__pb2._VOMCIMESSAGE,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_VOMCIMESSAGESBI)

DESCRIPTOR.services_by_name['VomciMessageSbi'] = _VOMCIMESSAGESBI

# @@protoc_insertion_point(module_scope)
