# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tr451_vomci_sbi_message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tr451_vomci_sbi_message.proto',
  package='tr451_vomci_sbi_message.v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x1dtr451_vomci_sbi_message.proto\x12\x1atr451_vomci_sbi_message.v1\"\x1e\n\x05Hello\x12\x15\n\rendpoint_name\x18\x01 \x01(\t\"T\n\x11HelloVomciRequest\x12?\n\x14local_endpoint_hello\x18\x01 \x01(\x0b\x32!.tr451_vomci_sbi_message.v1.Hello\"V\n\x12HelloVomciResponse\x12@\n\x15remote_endpoint_hello\x18\x01 \x01(\x0b\x32!.tr451_vomci_sbi_message.v1.Hello\"\xb1\x01\n\x0cVomciMessage\x12\x1a\n\x12request_payload_id\x18\x01 \x01(\t\x12;\n\terror_msg\x18\x02 \x01(\x0b\x32&.tr451_vomci_sbi_message.v1.VomciErrorH\x00\x12\x41\n\x0fomci_packet_msg\x18\x03 \x01(\x0b\x32&.tr451_vomci_sbi_message.v1.OmciPacketH\x00\x42\x05\n\x03msg\"\xba\x01\n\nVomciError\x12I\n\nerror_code\x18\x01 \x01(\x0e\x32\x35.tr451_vomci_sbi_message.v1.VomciError.VomciErrorCode\x12\x19\n\x11\x65rror_description\x18\x02 \x01(\t\"F\n\x0eVomciErrorCode\x12\x11\n\rERROR_GENERAL\x10\x00\x12\x0c\n\x08NO_ROUTE\x10\x01\x12\x13\n\x0fREQUEST_TIMEOUT\x10\x02\"E\n\tOnuHeader\x12\x10\n\x08olt_name\x18\x01 \x01(\t\x12\x16\n\x0e\x63hnl_term_name\x18\x02 \x01(\t\x12\x0e\n\x06onu_id\x18\x03 \x01(\r\"0\n\x0eOmciMsgRetrans\x12\x0e\n\x06t_maxi\x18\x01 \x01(\r\x12\x0e\n\x06r_maxi\x18\x02 \x01(\r\"S\n\x0bMessageInfo\x12\x44\n\x10omci_msg_retrans\x18\x01 \x01(\x0b\x32*.tr451_vomci_sbi_message.v1.OmciMsgRetrans\"\x8f\x01\n\nOmciPacket\x12\x35\n\x06header\x18\x01 \x01(\x0b\x32%.tr451_vomci_sbi_message.v1.OnuHeader\x12\x39\n\x08msg_info\x18\x02 \x01(\x0b\x32\'.tr451_vomci_sbi_message.v1.MessageInfo\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\x62\x06proto3'
)



_VOMCIERROR_VOMCIERRORCODE = _descriptor.EnumDescriptor(
  name='VomciErrorCode',
  full_name='tr451_vomci_sbi_message.v1.VomciError.VomciErrorCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ERROR_GENERAL', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NO_ROUTE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REQUEST_TIMEOUT', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=564,
  serialized_end=634,
)
_sym_db.RegisterEnumDescriptor(_VOMCIERROR_VOMCIERRORCODE)


_HELLO = _descriptor.Descriptor(
  name='Hello',
  full_name='tr451_vomci_sbi_message.v1.Hello',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='endpoint_name', full_name='tr451_vomci_sbi_message.v1.Hello.endpoint_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=91,
)


_HELLOVOMCIREQUEST = _descriptor.Descriptor(
  name='HelloVomciRequest',
  full_name='tr451_vomci_sbi_message.v1.HelloVomciRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='local_endpoint_hello', full_name='tr451_vomci_sbi_message.v1.HelloVomciRequest.local_endpoint_hello', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=177,
)


_HELLOVOMCIRESPONSE = _descriptor.Descriptor(
  name='HelloVomciResponse',
  full_name='tr451_vomci_sbi_message.v1.HelloVomciResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='remote_endpoint_hello', full_name='tr451_vomci_sbi_message.v1.HelloVomciResponse.remote_endpoint_hello', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=265,
)


_VOMCIMESSAGE = _descriptor.Descriptor(
  name='VomciMessage',
  full_name='tr451_vomci_sbi_message.v1.VomciMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_payload_id', full_name='tr451_vomci_sbi_message.v1.VomciMessage.request_payload_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_msg', full_name='tr451_vomci_sbi_message.v1.VomciMessage.error_msg', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='omci_packet_msg', full_name='tr451_vomci_sbi_message.v1.VomciMessage.omci_packet_msg', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='msg', full_name='tr451_vomci_sbi_message.v1.VomciMessage.msg',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=268,
  serialized_end=445,
)


_VOMCIERROR = _descriptor.Descriptor(
  name='VomciError',
  full_name='tr451_vomci_sbi_message.v1.VomciError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error_code', full_name='tr451_vomci_sbi_message.v1.VomciError.error_code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_description', full_name='tr451_vomci_sbi_message.v1.VomciError.error_description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _VOMCIERROR_VOMCIERRORCODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=448,
  serialized_end=634,
)


_ONUHEADER = _descriptor.Descriptor(
  name='OnuHeader',
  full_name='tr451_vomci_sbi_message.v1.OnuHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='olt_name', full_name='tr451_vomci_sbi_message.v1.OnuHeader.olt_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chnl_term_name', full_name='tr451_vomci_sbi_message.v1.OnuHeader.chnl_term_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='onu_id', full_name='tr451_vomci_sbi_message.v1.OnuHeader.onu_id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=636,
  serialized_end=705,
)


_OMCIMSGRETRANS = _descriptor.Descriptor(
  name='OmciMsgRetrans',
  full_name='tr451_vomci_sbi_message.v1.OmciMsgRetrans',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='t_maxi', full_name='tr451_vomci_sbi_message.v1.OmciMsgRetrans.t_maxi', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='r_maxi', full_name='tr451_vomci_sbi_message.v1.OmciMsgRetrans.r_maxi', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=707,
  serialized_end=755,
)


_MESSAGEINFO = _descriptor.Descriptor(
  name='MessageInfo',
  full_name='tr451_vomci_sbi_message.v1.MessageInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='omci_msg_retrans', full_name='tr451_vomci_sbi_message.v1.MessageInfo.omci_msg_retrans', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=757,
  serialized_end=840,
)


_OMCIPACKET = _descriptor.Descriptor(
  name='OmciPacket',
  full_name='tr451_vomci_sbi_message.v1.OmciPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='tr451_vomci_sbi_message.v1.OmciPacket.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg_info', full_name='tr451_vomci_sbi_message.v1.OmciPacket.msg_info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='tr451_vomci_sbi_message.v1.OmciPacket.payload', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=843,
  serialized_end=986,
)

_HELLOVOMCIREQUEST.fields_by_name['local_endpoint_hello'].message_type = _HELLO
_HELLOVOMCIRESPONSE.fields_by_name['remote_endpoint_hello'].message_type = _HELLO
_VOMCIMESSAGE.fields_by_name['error_msg'].message_type = _VOMCIERROR
_VOMCIMESSAGE.fields_by_name['omci_packet_msg'].message_type = _OMCIPACKET
_VOMCIMESSAGE.oneofs_by_name['msg'].fields.append(
  _VOMCIMESSAGE.fields_by_name['error_msg'])
_VOMCIMESSAGE.fields_by_name['error_msg'].containing_oneof = _VOMCIMESSAGE.oneofs_by_name['msg']
_VOMCIMESSAGE.oneofs_by_name['msg'].fields.append(
  _VOMCIMESSAGE.fields_by_name['omci_packet_msg'])
_VOMCIMESSAGE.fields_by_name['omci_packet_msg'].containing_oneof = _VOMCIMESSAGE.oneofs_by_name['msg']
_VOMCIERROR.fields_by_name['error_code'].enum_type = _VOMCIERROR_VOMCIERRORCODE
_VOMCIERROR_VOMCIERRORCODE.containing_type = _VOMCIERROR
_MESSAGEINFO.fields_by_name['omci_msg_retrans'].message_type = _OMCIMSGRETRANS
_OMCIPACKET.fields_by_name['header'].message_type = _ONUHEADER
_OMCIPACKET.fields_by_name['msg_info'].message_type = _MESSAGEINFO
DESCRIPTOR.message_types_by_name['Hello'] = _HELLO
DESCRIPTOR.message_types_by_name['HelloVomciRequest'] = _HELLOVOMCIREQUEST
DESCRIPTOR.message_types_by_name['HelloVomciResponse'] = _HELLOVOMCIRESPONSE
DESCRIPTOR.message_types_by_name['VomciMessage'] = _VOMCIMESSAGE
DESCRIPTOR.message_types_by_name['VomciError'] = _VOMCIERROR
DESCRIPTOR.message_types_by_name['OnuHeader'] = _ONUHEADER
DESCRIPTOR.message_types_by_name['OmciMsgRetrans'] = _OMCIMSGRETRANS
DESCRIPTOR.message_types_by_name['MessageInfo'] = _MESSAGEINFO
DESCRIPTOR.message_types_by_name['OmciPacket'] = _OMCIPACKET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Hello = _reflection.GeneratedProtocolMessageType('Hello', (_message.Message,), {
  'DESCRIPTOR' : _HELLO,
  '__module__' : 'tr451_vomci_sbi_message_pb2'
  # @@protoc_insertion_point(class_scope:tr451_vomci_sbi_message.v1.Hello)
  })
_sym_db.RegisterMessage(Hello)

HelloVomciRequest = _reflection.GeneratedProtocolMessageType('HelloVomciRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOVOMCIREQUEST,
  '__module__' : 'tr451_vomci_sbi_message_pb2'
  # @@protoc_insertion_point(class_scope:tr451_vomci_sbi_message.v1.HelloVomciRequest)
  })
_sym_db.RegisterMessage(HelloVomciRequest)

HelloVomciResponse = _reflection.GeneratedProtocolMessageType('HelloVomciResponse', (_message.Message,), {
  'DESCRIPTOR' : _HELLOVOMCIRESPONSE,
  '__module__' : 'tr451_vomci_sbi_message_pb2'
  # @@protoc_insertion_point(class_scope:tr451_vomci_sbi_message.v1.HelloVomciResponse)
  })
_sym_db.RegisterMessage(HelloVomciResponse)

VomciMessage = _reflection.GeneratedProtocolMessageType('VomciMessage', (_message.Message,), {
  'DESCRIPTOR' : _VOMCIMESSAGE,
  '__module__' : 'tr451_vomci_sbi_message_pb2'
  # @@protoc_insertion_point(class_scope:tr451_vomci_sbi_message.v1.VomciMessage)
  })
_sym_db.RegisterMessage(VomciMessage)

VomciError = _reflection.GeneratedProtocolMessageType('VomciError', (_message.Message,), {
  'DESCRIPTOR' : _VOMCIERROR,
  '__module__' : 'tr451_vomci_sbi_message_pb2'
  # @@protoc_insertion_point(class_scope:tr451_vomci_sbi_message.v1.VomciError)
  })
_sym_db.RegisterMessage(VomciError)

OnuHeader = _reflection.GeneratedProtocolMessageType('OnuHeader', (_message.Message,), {
  'DESCRIPTOR' : _ONUHEADER,
  '__module__' : 'tr451_vomci_sbi_message_pb2'
  # @@protoc_insertion_point(class_scope:tr451_vomci_sbi_message.v1.OnuHeader)
  })
_sym_db.RegisterMessage(OnuHeader)

OmciMsgRetrans = _reflection.GeneratedProtocolMessageType('OmciMsgRetrans', (_message.Message,), {
  'DESCRIPTOR' : _OMCIMSGRETRANS,
  '__module__' : 'tr451_vomci_sbi_message_pb2'
  # @@protoc_insertion_point(class_scope:tr451_vomci_sbi_message.v1.OmciMsgRetrans)
  })
_sym_db.RegisterMessage(OmciMsgRetrans)

MessageInfo = _reflection.GeneratedProtocolMessageType('MessageInfo', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEINFO,
  '__module__' : 'tr451_vomci_sbi_message_pb2'
  # @@protoc_insertion_point(class_scope:tr451_vomci_sbi_message.v1.MessageInfo)
  })
_sym_db.RegisterMessage(MessageInfo)

OmciPacket = _reflection.GeneratedProtocolMessageType('OmciPacket', (_message.Message,), {
  'DESCRIPTOR' : _OMCIPACKET,
  '__module__' : 'tr451_vomci_sbi_message_pb2'
  # @@protoc_insertion_point(class_scope:tr451_vomci_sbi_message.v1.OmciPacket)
  })
_sym_db.RegisterMessage(OmciPacket)


# @@protoc_insertion_point(module_scope)
