# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tr451_vomci_nbi_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from nbi.grpc.service_definition import tr451_vomci_nbi_message_pb2 as tr451__vomci__nbi__message__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tr451_vomci_nbi_service.proto',
  package='tr451_vomci_nbi_service.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1dtr451_vomci_nbi_service.proto\x12\x1atr451_vomci_nbi_service.v1\x1a\x1dtr451_vomci_nbi_message.proto\x1a\x1bgoogle/protobuf/empty.proto2\x98\x05\n\x0fVomciMessageNbi\x12I\n\x05Hello\x12\x1f.tr451_vomci_nbi_message.v1.Msg\x1a\x1f.tr451_vomci_nbi_message.v1.Msg\x12K\n\x07GetData\x12\x1f.tr451_vomci_nbi_message.v1.Msg\x1a\x1f.tr451_vomci_nbi_message.v1.Msg\x12Q\n\rReplaceConfig\x12\x1f.tr451_vomci_nbi_message.v1.Msg\x1a\x1f.tr451_vomci_nbi_message.v1.Msg\x12W\n\x13UpdateConfigReplica\x12\x1f.tr451_vomci_nbi_message.v1.Msg\x1a\x1f.tr451_vomci_nbi_message.v1.Msg\x12X\n\x14UpdateConfigInstance\x12\x1f.tr451_vomci_nbi_message.v1.Msg\x1a\x1f.tr451_vomci_nbi_message.v1.Msg\x12G\n\x03RPC\x12\x1f.tr451_vomci_nbi_message.v1.Msg\x1a\x1f.tr451_vomci_nbi_message.v1.Msg\x12J\n\x06\x41\x63tion\x12\x1f.tr451_vomci_nbi_message.v1.Msg\x1a\x1f.tr451_vomci_nbi_message.v1.Msg\x12R\n\x15ListenForNotification\x12\x16.google.protobuf.Empty\x1a\x1f.tr451_vomci_nbi_message.v1.Msg0\x01\x62\x06proto3'
  ,
  dependencies=[tr451__vomci__nbi__message__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_VOMCIMESSAGENBI = _descriptor.ServiceDescriptor(
  name='VomciMessageNbi',
  full_name='tr451_vomci_nbi_service.v1.VomciMessageNbi',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=122,
  serialized_end=786,
  methods=[
  _descriptor.MethodDescriptor(
    name='Hello',
    full_name='tr451_vomci_nbi_service.v1.VomciMessageNbi.Hello',
    index=0,
    containing_service=None,
    input_type=tr451__vomci__nbi__message__pb2._MSG,
    output_type=tr451__vomci__nbi__message__pb2._MSG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetData',
    full_name='tr451_vomci_nbi_service.v1.VomciMessageNbi.GetData',
    index=1,
    containing_service=None,
    input_type=tr451__vomci__nbi__message__pb2._MSG,
    output_type=tr451__vomci__nbi__message__pb2._MSG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ReplaceConfig',
    full_name='tr451_vomci_nbi_service.v1.VomciMessageNbi.ReplaceConfig',
    index=2,
    containing_service=None,
    input_type=tr451__vomci__nbi__message__pb2._MSG,
    output_type=tr451__vomci__nbi__message__pb2._MSG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateConfigReplica',
    full_name='tr451_vomci_nbi_service.v1.VomciMessageNbi.UpdateConfigReplica',
    index=3,
    containing_service=None,
    input_type=tr451__vomci__nbi__message__pb2._MSG,
    output_type=tr451__vomci__nbi__message__pb2._MSG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateConfigInstance',
    full_name='tr451_vomci_nbi_service.v1.VomciMessageNbi.UpdateConfigInstance',
    index=4,
    containing_service=None,
    input_type=tr451__vomci__nbi__message__pb2._MSG,
    output_type=tr451__vomci__nbi__message__pb2._MSG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RPC',
    full_name='tr451_vomci_nbi_service.v1.VomciMessageNbi.RPC',
    index=5,
    containing_service=None,
    input_type=tr451__vomci__nbi__message__pb2._MSG,
    output_type=tr451__vomci__nbi__message__pb2._MSG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Action',
    full_name='tr451_vomci_nbi_service.v1.VomciMessageNbi.Action',
    index=6,
    containing_service=None,
    input_type=tr451__vomci__nbi__message__pb2._MSG,
    output_type=tr451__vomci__nbi__message__pb2._MSG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ListenForNotification',
    full_name='tr451_vomci_nbi_service.v1.VomciMessageNbi.ListenForNotification',
    index=7,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=tr451__vomci__nbi__message__pb2._MSG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_VOMCIMESSAGENBI)

DESCRIPTOR.services_by_name['VomciMessageNbi'] = _VOMCIMESSAGENBI

# @@protoc_insertion_point(module_scope)
